### ISSUE TITLE
Error TypeError: 'module' object is not callable with Python functions

### ISSUE THREAD

**Issue by adjohn** [iopipe/serverless-iopipe-layers#13]
Using this stock example: https://github.com/serverless/examples/tree/master/aws-python-rest-api-with-dynamodb

I added the `serverless-iopipe-layers` plugin, set the token, deployed, and then tried 

`curl -X POST https://xxxxx.execute-api.us-east-1.amazonaws.com/dev/todos --data '{ "text": "Learn Serverless" }'`  (following the example README)

I see the error coming through to IOpipe which is:
```
Traceback (most recent call last):
  File "/opt/python/lib/python2.7/site-packages/iopipe/agent.py", line 149, in wrapped
    result = func(event, context)
  File "/opt/python/lib/python2.7/site-packages/iopipe/handler.py", line 11, in wrapper
    return get_wrapped_handler()(event, context)
TypeError: 'module' object is not callable
```

**Comment by kolanos** [comment]
This appears to be an issue specific to `python2.7`. Changing the runtime to `python3.6` or `python3.7` resolves the error.
