### ISSUE TITLE
Support enabling debug via AWS Env Var

### ISSUE THREAD

**Issue by adjohn** [iopipe/serverless-iopipe-layers#18]
Currently debug can only be enabled by modifying the serverless.yml and then redeploying the function.  It would be easier to debug if this supports setting debug via the `IOPIPE_DEBUG` AWS environment variable.

**Comment by kolanos** [comment]
@adjohn Have you verified this? All `debug` does is add the `IOPIPE_DEBUG` environment variable to the function.

**Comment by kolanos** [comment]
Closing as the layers support `IOPIPE_DEBUG`.
